[%
    T = {
        configure_1                                = "IntranetUserJS: Restrict patron modification by category Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Restrict patron modification by category &rsaquo; Configuration",
        configure_5                                = "Restricted customer types separeted by commas (E.g. CLERK,AUTOM,API):",
        configure_6                                = "Save configuration",
        configure_7                                = "Upgrade status",
        configure_8                                = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: Restrict patron modification by category",
        viewjs_2                                   = "&rsaquo; RestrictPatronModification &rsaquo; View JS Tool",
    }
%]
