[%
    T = {
        configure_1                                = "IntranetUserJS: Asiakastietojen muokkauksen rajoittaminen asiakastyypin mukaan - Asetukset",
        configure_2                                = "Etusivu",
        configure_3                                = "Laajennukset",
        configure_4                                = "&rsaquo; IntranetUserJS: Asiakastietojen muokkauksen rajoittaminen asiakastyypin mukaan &rsaquo; Asetukset",
        configure_5                                = "Rajoitettavat asiakastyypit pilkulla erotettuna (Esim. VIRKAILIJA,AUTOM,API):",
        configure_6                                = "Tallenna asetukset",
        configure_7                                = "Päivityksen tila",
        configure_8                                = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Asiakastietojen muokkauksen rajoittaminen asiakastyypin mukaan",
        viewjs_2                                   = "&rsaquo; RestrictPatronModification &rsaquo; Näytä JS-työkalu",
    }
%]