[%
    T = {
        configure_1                                = "IntranetUserJS: Begränsa ändring av låntagare per kategori - Konfiguration",
        configure_2                                = "Hem",
        configure_3                                = "Moduler",
        configure_4                                = "&rsaquo; IntranetUserJS: Begränsa ändring av låntagare per kategori &rsaquo; Konfiguration",
        configure_5                                = "Begränsade låntagarkategorier separerade med kommatecken (T.ex. TJAESTE,AUTOM,API):",
        configure_6                                = "Spara konfiguration",
        configure_7                                = "Uppgraderingsstatus",
        configure_8                                = "Modulen har aldrig uppgraderats.",
        viewjs_1                                   = "IntranetUserJS: Begränsa ändring av låntagare per kategori",
        viewjs_2                                   = "&rsaquo; RestrictPatronModification &rsaquo; Visa JS-verktyg",
    }
%]